env:
   global:
     - CONAN_REFERENCE: "plugin.node"
     - CONAN_USERNAME: "yjjnls"
     - CONAN_LOGIN_USERNAME: "yjjnls"
     - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/yjjnls/testing"
    #  - CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "2.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64


install:
  - sudo pip install conan --upgrade
  - sudo pip install conan_package_tools bincrafters_package_tools
  - sudo conan user
  - pushd ~
  - wget https://nodejs.org/dist/v10.4.0/node-v10.4.0-linux-x64.tar.xz 
  - tar -xf node-v10.4.0-linux-x64.tar.xz
  - sudo cp -rf node-v10.4.0-linux-x64/* /usr/local
  - popd
  - sudo npm install -g node-gyp 
  - sudo node-gyp --version
  - sudo pkg-config --version
  - pushd ~
  - wget https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.11.3-Linux-x86_64.tar.gz
  - sudo cp -rf cmake-3.11.3-Linux-x86_64/bin /usr/local
  - sudo cp -rf cmake-3.11.3-Linux-x86_64/share /usr/local
  - popd


script:
  - sudo conan create . yjjnls/testing
