env:
   global:
    #  - CONAN_REFERENCE: "plugin.node/0.5.3-dev"
     - CONAN_USERNAME: "yjjnls"
     - CONAN_LOGIN_USERNAME: "yjjnls"
     - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
     - CONAN_PASSWORD: 1c2adb5a99c8fbdbfe203e012e37a734aa142f68
        # secure: s+BOuh3hBuWX0CC7gWS+wExeBRmKVO+EcijzMovdqV+95A+O7rMo2D/LnBjxW0IY
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/yjjnls/testing"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "2.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

#       # - <<: *linux
#       #   env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env:  CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=yjjnls/conangcc49 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64

install:
#   - yes|sudo add-apt-repository ppa:ubuntu-toolchain-r/test
#   - yes|sudo apt-get update
#   - sudo apt-get install gcc-4.9
#   - sudo apt-get install g++-4.9
#   - sudo rm -f /usr/bin/gcc /usr/bin/g++  
#   - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc  
#   - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo pip install conan --upgrade
  - sudo pip install conan_package_tools bincrafters_package_tools
  - sudo pip install shell
  - sudo conan user
#   - pushd ~
#   - wget https://nodejs.org/dist/v10.4.0/node-v10.4.0-linux-x64.tar.xz 
#   - tar -xf node-v10.4.0-linux-x64.tar.xz
#   - sudo cp -rf node-v10.4.0-linux-x64/* /usr/local
#   - popd
#   - sudo npm install -g node-gyp 
#   - sudo node-gyp --version
#   - sudo pkg-config --version
#   - pushd ~
#   - wget https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.tar.gz
#   - tar -xf cmake-3.11.3-Linux-x86_64.tar.gz
#   - sudo cp -rf cmake-3.11.3-Linux-x86_64/bin /usr/local
#   - sudo cp -rf cmake-3.11.3-Linux-x86_64/share /usr/local
#   - popd

# before_script:
#   - sudo gcc --version
#   - sudo python --version
#   - sudo cmake --version
#   - sudo node --version

script:
  # - sudo conan create . yjjnls/testing
  - sudo python build.py